import type { Course } from './coursesApi';
// ─── Provider colour map ──────────────────────────────────────────────────────
export const PROVIDER_COLORS: Record<string, string> = {
  Coursera: 'bg-blue-100 text-blue-700 border-blue-200',
  Udemy: 'bg-orange-100 text-orange-700 border-orange-200',
  edX: 'bg-red-100 text-red-700 border-red-200',
  NPTEL: 'bg-green-100 text-green-700 border-green-200',
  NQR: 'bg-gray-100 text-gray-600 border-gray-200',
};

// ─── 25 Real Courses (direct enrollment URLs) ─────────────────────────────────
export const realCourses: Course[] = [
  // ── Coursera ──────────────────────────────────────────────────────────────
  {
    title: 'Machine Learning Specialization',
    description: 'Master ML fundamentals, supervised/unsupervised learning, and build real-world projects with Andrew Ng — the world\'s most popular ML course.',
    source_url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipnemtsi.cloudfront.net/Role/Machine-Learning-Engineer.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25',
    sector: 'AI & ML', level: 'Intermediate', duration: '3 Months',
    instructor: 'Andrew Ng', provider: 'Coursera', rating: 4.9, enrolledCount: '285k',
    isCurated: true,
  },
  {
    title: 'Deep Learning Specialization',
    description: 'Deep dive into neural networks, CNNs, RNNs, and Transformers. Build AI applications — taught by Andrew Ng at DeepLearning.AI.',
    source_url: 'https://www.coursera.org/specializations/deep-learning',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/cb/3c4030d65011e682d8b14e2f0915fa/shutterstock_226881610.jpg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25',
    sector: 'AI & ML', level: 'Advanced', duration: '5 Months',
    instructor: 'Andrew Ng', provider: 'Coursera', rating: 4.9, enrolledCount: '320k',
    isCurated: true,
  },
  {
    title: 'Generative AI with Large Language Models',
    description: 'Learn GenAI fundamentals, fine-tune LLMs, and deploy production-grade AI apps with AWS and DeepLearning.AI.',
    source_url: 'https://www.coursera.org/learn/generative-ai-with-llms',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/97/fb23a9d2ad4f7bae788e0db4ec32f0/GenAI-LLMs.png?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25',
    sector: 'AI & ML', level: 'Intermediate', duration: '3 Weeks',
    instructor: 'DeepLearning.AI × AWS', provider: 'Coursera', rating: 4.8, enrolledCount: '95k',
    isCurated: true,
  },
  {
    title: 'Google Data Analytics Certificate',
    description: 'Learn data analysis with spreadsheets, SQL, R, and Tableau. Earn a Google certificate and prepare for a data analyst role.',
    source_url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/meta_images/generated/XDP/XDP~SPECIALIZATION!~google-data-analytics/XDP~SPECIALIZATION!~google-data-analytics.jpeg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25',
    sector: 'Computer Science', level: 'Beginner', duration: '6 Months',
    instructor: 'Google Career Certificates', provider: 'Coursera', rating: 4.8, enrolledCount: '1.8M',
    isCurated: true,
  },
  {
    title: 'IBM Data Science Professional Certificate',
    description: 'Hands-on data science skills: Python, SQL, machine learning, and data visualisation with IBM tools and real datasets.',
    source_url: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/meta_images/generated/XDP/XDP~SPECIALIZATION!~ibm-data-science/XDP~SPECIALIZATION!~ibm-data-science.jpeg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25',
    sector: 'Computer Science', level: 'Beginner', duration: '5 Months',
    instructor: 'IBM Skills Network', provider: 'Coursera', rating: 4.7, enrolledCount: '520k',
    isCurated: true,
  },
  {
    title: 'Python for Everybody Specialization',
    description: 'Learn Python fundamentals, data structures, web scraping, and databases in this beginner-friendly specialisation by Dr. Chuck.',
    source_url: 'https://www.coursera.org/specializations/python',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/meta_images/generated/XDP/XDP~SPECIALIZATION!~python/XDP~SPECIALIZATION!~python.jpeg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25',
    sector: 'Computer Science', level: 'Beginner', duration: '8 Months',
    instructor: 'Dr. Chuck Severance', provider: 'Coursera', rating: 4.8, enrolledCount: '1.3M',
    isCurated: true,
  },
  {
    title: 'Meta Full-Stack Developer Certificate',
    description: 'Build full-stack web applications with React, Node.js, and databases. Certified by Meta — the company behind Facebook and Instagram.',
    source_url: 'https://www.coursera.org/professional-certificates/meta-full-stack-developer',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://s3.amazonaws.com/coursera_assets/meta_images/generated/XDP/XDP~SPECIALIZATION!~meta-full-stack-developer/XDP~SPECIALIZATION!~meta-full-stack-developer.jpeg?auto=format%2Ccompress&dpr=1&w=330&h=330&fit=fill&q=25',
    sector: 'Computer Science', level: 'Intermediate', duration: '9 Months',
    instructor: 'Meta Staff', provider: 'Coursera', rating: 4.7, enrolledCount: '130k',
    isCurated: true,
  },
  {
    title: 'Google Cybersecurity Certificate',
    description: 'Gain job-ready cybersecurity skills: network security, Linux, SQL, Python, and SIEM tools — certified by Google.',
    source_url: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Beginner', duration: '6 Months',
    instructor: 'Google Career Certificates', provider: 'Coursera', rating: 4.8, enrolledCount: '210k',
    isCurated: true,
  },
  {
    title: 'IBM AI Engineering Professional Certificate',
    description: 'Scale AI skills with deep learning, computer vision, NLP, and MLOps — build and deploy AI models using IBM Watson.',
    source_url: 'https://www.coursera.org/professional-certificates/ai-engineer',
    image: 'https://images.unsplash.com/photo-1561736778-92e52a7769ef?w=600&q=80&auto=format&fit=crop',
    sector: 'AI & ML', level: 'Advanced', duration: '8 Months',
    instructor: 'IBM Skills Network', provider: 'Coursera', rating: 4.6, enrolledCount: '85k',
    isCurated: true,
  },
  {
    title: 'Natural Language Processing Specialization',
    description: 'Build NLP models for sentiment analysis, machine translation, and question answering using deep learning — by DeepLearning.AI.',
    source_url: 'https://www.coursera.org/specializations/natural-language-processing',
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=600&q=80&auto=format&fit=crop',
    sector: 'AI & ML', level: 'Advanced', duration: '4 Months',
    instructor: 'DeepLearning.AI', provider: 'Coursera', rating: 4.7, enrolledCount: '78k',
    isCurated: true,
  },
  {
    title: 'Cloud Computing Specialization',
    description: 'Master cloud architecture, distributed systems, and cloud application development on AWS and Azure.',
    source_url: 'https://www.coursera.org/specializations/cloud-computing',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Intermediate', duration: '6 Months',
    instructor: 'Univ. of Illinois', provider: 'Coursera', rating: 4.5, enrolledCount: '60k',
    isCurated: true,
  },
  {
    title: 'Introduction to Computer Science',
    description: 'Harvard\'s legendary CS50 on Coursera — algorithms, data structures, web development, and programming fundamentals. Zero experience needed.',
    source_url: 'https://www.coursera.org/learn/introduction-computer-science',
    image: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Beginner', duration: '10 Weeks',
    instructor: 'David J. Malan', provider: 'Coursera', rating: 4.9, enrolledCount: '400k',
    isCurated: true,
  },

  // ── Udemy ──────────────────────────────────────────────────────────────────
  {
    title: '100 Days of Code: The Complete Python Pro Bootcamp',
    description: '100 projects in 100 days — Python web development, data science, automation, and more. The #1 Python course on Udemy.',
    source_url: 'https://www.udemy.com/course/100-days-of-code/',
    image: 'https://img-b.udemycdn.com/course/480x270/2776760_f176_10.jpg',
    sector: 'Computer Science', level: 'Beginner', duration: '60 Hours',
    instructor: 'Angela Yu', provider: 'Udemy', rating: 4.8, enrolledCount: '1.1M',
    isCurated: true,
  },
  {
    title: 'The Complete Web Developer Bootcamp',
    description: 'Full stack web development with HTML, CSS, JavaScript, Node.js, React, MongoDB from scratch. Hundreds of coding exercises.',
    source_url: 'https://www.udemy.com/course/the-web-developer-bootcamp/',
    image: 'https://img-b.udemycdn.com/course/480x270/625204_436a_3.jpg',
    sector: 'Computer Science', level: 'Beginner', duration: '65 Hours',
    instructor: 'Colt Steele', provider: 'Udemy', rating: 4.7, enrolledCount: '900k',
    isCurated: true,
  },
  {
    title: 'Machine Learning A–Z: AI, Python & R',
    description: 'Hands-on machine learning with scikit-learn, TensorFlow, and R. Regression, classification, clustering, NLP, and reinforcement learning.',
    source_url: 'https://www.udemy.com/course/machinelearning/',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&q=80&auto=format&fit=crop',
    sector: 'AI & ML', level: 'Beginner', duration: '44 Hours',
    instructor: 'Kirill Eremenko', provider: 'Udemy', rating: 4.5, enrolledCount: '800k',
    isCurated: true,
  },
  {
    title: 'React — The Complete Guide',
    description: 'Dive deep into React.js — Hooks, Redux, React Router, Next.js, and performance optimisation. The most comprehensive React course.',
    source_url: 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/',
    image: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Beginner', duration: '68 Hours',
    instructor: 'Maximilian Schwarzmüller', provider: 'Udemy', rating: 4.6, enrolledCount: '750k',
    isCurated: true,
  },
  {
    title: 'Docker & Kubernetes: The Practical Guide',
    description: 'Master Docker and Kubernetes from scratch — build, ship, and orchestrate containers across local and cloud environments.',
    source_url: 'https://www.udemy.com/course/docker-kubernetes-the-practical-guide/',
    image: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Intermediate', duration: '24 Hours',
    instructor: 'Maximilian Schwarzmüller', provider: 'Udemy', rating: 4.7, enrolledCount: '220k',
    isCurated: true,
  },
  {
    title: 'The Complete SQL Bootcamp',
    description: 'Master SQL for data analysis — queries, joins, subqueries, window functions, and PostgreSQL. No prior experience needed.',
    source_url: 'https://www.udemy.com/course/the-complete-sql-bootcamp/',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Beginner', duration: '9 Hours',
    instructor: 'Jose Portilla', provider: 'Udemy', rating: 4.7, enrolledCount: '500k',
    isCurated: true,
  },

  // ── edX ───────────────────────────────────────────────────────────────────
  {
    title: "CS50: Introduction to Computer Science",
    description: "Harvard's introduction to the intellectual enterprises of computer science. Free to audit — the most widely taken CS course in history.",
    source_url: 'https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science',
    image: 'https://prod-discovery.edx-cdn.org/media/course/image/84ab3a15-bfa3-4700-be46-320d0f507b99-fc9ec178b668.small.jpg',
    sector: 'Computer Science', level: 'Beginner', duration: '12 Weeks',
    instructor: 'David J. Malan', provider: 'edX', rating: 4.9, enrolledCount: '3M',
    isCurated: true,
  },
  {
    title: 'MIT MicroMasters: Statistics & Data Science',
    description: 'Rigorous MIT curriculum in statistics, machine learning, and data science. Earns credit toward MIT\'s Master\'s program.',
    source_url: 'https://www.edx.org/masters/micromasters/mitx-statistics-and-data-science',
    image: 'https://prod-discovery.edx-cdn.org/media/programs/image/b822d6ed-967a-4299-a1b7-9f66455ab7da-9c864b4c48de.small.jpg',
    sector: 'AI & ML', level: 'Advanced', duration: '1 Year',
    instructor: 'MIT Faculty', provider: 'edX', rating: 4.8, enrolledCount: '140k',
    isCurated: true,
  },
  {
    title: 'IBM Applied AI Professional Certificate',
    description: 'Build AI applications with Python, Watson APIs, and OpenCV — computer vision, NLP, and AI-powered web apps.',
    source_url: 'https://www.edx.org/certificates/professional-certificate/ibm-applied-ai',
    image: 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=600&q=80&auto=format&fit=crop',
    sector: 'AI & ML', level: 'Intermediate', duration: '6 Months',
    instructor: 'IBM Skills Network', provider: 'edX', rating: 4.6, enrolledCount: '55k',
    isCurated: true,
  },
  {
    title: 'Blockchain for Business (Hyperledger)',
    description: 'Understand enterprise blockchain, Hyperledger Fabric, and distributed ledger applications in supply chain, finance, and healthcare.',
    source_url: 'https://www.edx.org/learn/blockchain/the-linux-foundation-blockchain-for-business-an-introduction-to-hyperledger-technologies',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Beginner', duration: '8 Weeks',
    instructor: 'Linux Foundation', provider: 'edX', rating: 4.5, enrolledCount: '75k',
    isCurated: true,
  },

  // ── NPTEL ─────────────────────────────────────────────────────────────────
  {
    title: 'Machine Learning (NPTEL — IIT Madras)',
    description: 'Comprehensive ML course from IIT Madras — regression, classification, SVM, decision trees, clustering, and neural networks. Free with certificate.',
    source_url: 'https://nptel.ac.in/courses/106/105/106105215/',
    image: 'https://nptel.ac.in/assets/images/nptel-logo.png',
    sector: 'AI & ML', level: 'Intermediate', duration: '8 Weeks',
    instructor: 'Prof. Sudeshna Sarkar', provider: 'NPTEL', rating: 4.7, enrolledCount: '120k',
    isCurated: true,
  },
  {
    title: 'Data Structures & Algorithms (NPTEL — IIT Madras)',
    description: 'Core computer science: arrays, linked lists, trees, graphs, sorting algorithms, dynamic programming — with coding exercises. Free.',
    source_url: 'https://nptel.ac.in/courses/106/102/106102064/',
    image: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=600&q=80&auto=format&fit=crop',
    sector: 'Computer Science', level: 'Intermediate', duration: '8 Weeks',
    instructor: 'Prof. Naveen Garg', provider: 'NPTEL', rating: 4.8, enrolledCount: '200k',
    isCurated: true,
  },
  {
    title: 'Natural Language Processing (NPTEL — IIT Bombay)',
    description: 'NLP fundamentals — morphology, parsing, semantics, and statistical NLP — by IIT Bombay faculty. Free with NPTEL certificate option.',
    source_url: 'https://nptel.ac.in/courses/106/101/106101224/',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80&auto=format&fit=crop',
    sector: 'AI & ML', level: 'Advanced', duration: '8 Weeks',
    instructor: 'Prof. Pushpak Bhattacharyya', provider: 'NPTEL', rating: 4.6, enrolledCount: '90k',
    isCurated: true,
  },
];
export { Course };

